name: template-des
dependencies:
  - flake8=7.1.1
  - ipykernel=6.29.5
  - jinja2=3.1.4
  - joblib=1.4.2
  - nbformat=5.10.4
  - numpy=2.1.3
  - pandas=2.2.3
  - pip=24.3.1
  - plotly_express=0.4.1
  - pycodestyle=2.12.1
  - pytest=8.3.4
  - python=3.13.0
  - simpy=4.1.1
  - pip:
    - pycodestyle_magic==0.5