[build-system]
requires = ["flit"]
build-backend = "flit_core.buildapi"

[project]
name = "simulation"
dynamic = ["version", "description", "author"]
authors = [
  { name = "Amy Heather", email = "a.heather2@exeter.ac.uk" }
]
