# This file will lint the specified files/directories.

name: lint

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
      runs-on: ubuntu-latest
      steps:

        - name: Check out repository
          uses: actions/checkout@v4

        - name: Install python and dependencies
          uses: actions/setup-python@v4
          with:
            python-version: '3.13'
            cache: 'pip'
        - run: pip install -r requirements.txt

        - name: Lint model code
          run: |
            pylint ./simulation

        - name: Lint tests
          run: |
            pylint ./tests

        - name: Lint notebooks
          run: |
            nbqa pylint ./notebooks

        - name: Lint time-weighted averages notebook
          run: |
            nbqa pylint ./docs/time_weighted_averages.ipynb